# KDE
- name: Install KDE packages
  become: yes
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
    - kde
    - avahi
    - sddm
- name: sysrc settings
  community.general.sysrc:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
  loop:
    - {name: 'dbus_enable', value: "YES"}
    - {name: 'sddm_enable', value: "YES"}
    - {name: 'avahi_daemon_enable', value: "YES"}
- name: Increase message size for KDE
  become: yes
  ansible.posix.sysctl:
    name: "{{ item }}"
    value: "65536"
    state: present
  loop:
    - net.local.stream.recvspace
    - net.local.stream.sendspace
- name: Ensure SDDM defaults to X11 not Wayland
  ansible.builtin.lineinfile:
    path: /usr/local/etc/sddm.conf
    regexp: '^DisplayServer='
    line: 'DisplayServer=x11'
