# Framework Generic
- name: Make power button suspend instead of turning off
  ansible.posix.sysctl:
    name: hw.acpi.power_button_state
    value: "S3"
    state: present
- name: Ethernet setup
  when: ansible_facts['default_ipv4'] == 'ue0'
  block:
    - name: Configure Ethernet Expansion Card IPv4 DHCP
      become: true
      community.general.sysrc:
        name: ifconfig_ue0
        value: "DHCP"
        state: present
    - name: Configure Ethernet Expansion Card IPv6 DHCP
      become: true
      community.general.sysrc:
        name: ifconfig_ue0_ipv6
        value: "inet6 accept_rtadv"
        state: present
- name: Install webcamd related packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
    - webcamd
    - v4l-utils
    - v4l_compat
- name: Get webcam settings
  ansible.builtin.shell:
    cmd: set -o pipefail && webcamd -l | awk '/Webcam/ {gsub(/\[/, "", $0); gsub(/\]/, "", $0); sub(/^webcamd /, "", $0); print}'
  changed_when: false
  register: webcamd
- name: sysrc setting for webcamd flags
  community.general.sysrc:
    name: 'webcamd_0_flags'
    value: '{{ webcamd.stdout }}'
  notify: 'Restart webcamd'
- name: sysrc settings
  community.general.sysrc:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: value_present
  loop:
    - {name: 'webcamd_enable', value: 'YES'}
    - {name: 'kld_list', value: 'cuse'}
- name: Add user to video and webcamd groups
  ansible.builtin.user:
    name: ansible_facts["ansible_env"]["DOAS_USER"]
    groups: video,webcamd
    append: true
# GUI
- name: Install GUI
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
    - xorg
    - firefox
    - flameshot
    - noto-emoji
    - noto-tc
    - urwfonts

# TODO: Need to run this or add to config
# > xset fp+ /usr/local/share/fonts/urwfonts
# > xset fp rehash
