- hosts: localhost
  roles:
    - role: framework
    - role: intel
      when: ansible_architecture == "intel"
    - role: amd
      when: ansible_architecture == "amd64"
    - role: xorg
    - role: kde
  # - i3
  # - gnome
