# AMD
# TODO: Is there a custom driver for AMD?
# Intel has hwpstate_intel
# - name: Don't enable powerd
#   become: yes
#   community.general.sysrc:
#     name: powerd_enable
#     value: "YES"
#     state: present
- name: Install Linux GPU drivers
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
    - drm-kmod
    - gpu-firmware-kmod
- name: Load CPU kernel modules
  community.general.sysrc:
    name: kld_list
    value: "{{ item }}"
    state: value_present
  loop:
    - amdgpu
    - amdtemp
    - cpuctl
